---

# ทดลองทำ Linear Regression #2

---



จาก Library sklearn (หรือ scikit learn) เราจะเรียกใช้ datasets


In [1]:
from sklearn import datasets

นำเข้าข้อมูล (Load Dataset) : ในที่นี้ใช้ข้อมูล "Boston" ที่มีอยู่ใน sklearn 

In [3]:
boston = datasets.load_boston()

ทำการเก็บข้อมูล Features ต่าง ๆ ไว้ที่ตัวแปร X .. และ เก็บข้อมูล Target ไว้ที่ตัวแปร y 

In [4]:
X = boston.data
y = boston.target

In [5]:
print (X)
print (y)

[[6.3200e-03 1.8000e+01 2.3100e+00 ... 1.5300e+01 3.9690e+02 4.9800e+00]
 [2.7310e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9690e+02 9.1400e+00]
 [2.7290e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9283e+02 4.0300e+00]
 ...
 [6.0760e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 5.6400e+00]
 [1.0959e-01 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9345e+02 6.4800e+00]
 [4.7410e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 7.8800e+00]]
[24.  21.6 34.7 33.4 36.2 28.7 22.9 27.1 16.5 18.9 15.  18.9 21.7 20.4
 18.2 19.9 23.1 17.5 20.2 18.2 13.6 19.6 15.2 14.5 15.6 13.9 16.6 14.8
 18.4 21.  12.7 14.5 13.2 13.1 13.5 18.9 20.  21.  24.7 30.8 34.9 26.6
 25.3 24.7 21.2 19.3 20.  16.6 14.4 19.4 19.7 20.5 25.  23.4 18.9 35.4
 24.7 31.6 23.3 19.6 18.7 16.  22.2 25.  33.  23.5 19.4 22.  17.4 20.9
 24.2 21.7 22.8 23.4 24.1 21.4 20.  20.8 21.2 20.3 28.  23.9 24.8 22.9
 23.9 26.6 22.5 22.2 23.6 28.7 22.6 22.  22.9 25.  20.6 28.4 21.4 38.7
 43.8 33.2 27.5 26.5 18.6 19.3 20.1 19.5 19.5 20.4 19.8 19.

แสดงตัวอย่าง Feature Name ของ Boston dataset

In [6]:
print (boston.feature_names)

['CRIM' 'ZN' 'INDUS' 'CHAS' 'NOX' 'RM' 'AGE' 'DIS' 'RAD' 'TAX' 'PTRATIO'
 'B' 'LSTAT']


In [7]:
print (boston.data[0:5])
print (boston.target[0:5])

[[6.3200e-03 1.8000e+01 2.3100e+00 0.0000e+00 5.3800e-01 6.5750e+00
  6.5200e+01 4.0900e+00 1.0000e+00 2.9600e+02 1.5300e+01 3.9690e+02
  4.9800e+00]
 [2.7310e-02 0.0000e+00 7.0700e+00 0.0000e+00 4.6900e-01 6.4210e+00
  7.8900e+01 4.9671e+00 2.0000e+00 2.4200e+02 1.7800e+01 3.9690e+02
  9.1400e+00]
 [2.7290e-02 0.0000e+00 7.0700e+00 0.0000e+00 4.6900e-01 7.1850e+00
  6.1100e+01 4.9671e+00 2.0000e+00 2.4200e+02 1.7800e+01 3.9283e+02
  4.0300e+00]
 [3.2370e-02 0.0000e+00 2.1800e+00 0.0000e+00 4.5800e-01 6.9980e+00
  4.5800e+01 6.0622e+00 3.0000e+00 2.2200e+02 1.8700e+01 3.9463e+02
  2.9400e+00]
 [6.9050e-02 0.0000e+00 2.1800e+00 0.0000e+00 4.5800e-01 7.1470e+00
  5.4200e+01 6.0622e+00 3.0000e+00 2.2200e+02 1.8700e+01 3.9690e+02
  5.3300e+00]]
[24.  21.6 34.7 33.4 36.2]




---
เริ่มขั้นตอนการสร้าง (Train) / ทดสอบ (Test) Model


---




จาก Library sklearn
*   เรียกใช้งาน Linear Regression ซึ่งอยู่ใน linear model
*   เรียกใช้งาน train / test split (การแบ่งข้อมูล train / test) ซึ่งอยู่ใน model selection


In [8]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split



*   ทำการแบ่งข้อมูล train (ใช้สร้าง Model) / test (ใช้ทดสอบ Model) 
*   สามารถกำหนด test size ได้ (ค่า test_size = 0.2 หมายถึง 20% เป็นข้อมูล test) 



In [12]:
X_train, X_test, y_train, y_test = train_test_split(boston.data, boston.target, test_size = 0.2)



*   เพื่อดูขนาดของข้อมูล train และ ข้อมูล test



In [13]:
print (X_train.shape)
print (X_test.shape)

(404, 13)
(102, 13)


กำหนด Linear Regression Model ในชื่อตัวแปร **"LR"** (กำหนดค่า Normalize = True)

In [14]:
LR = LinearRegression(normalize=True)

ทำการ Train model ด้วยข้อมูล X_train, y_train

In [15]:
LR.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=True)

วัดประสิทธิภาพของ Model โดยใช้ข้อมูล X_test, y_test ..

In [16]:
y_pred = LR.predict(X_test) 

In [21]:
from sklearn.metrics import mean_squared_error, r2_score
import numpy as np

rmse = np.sqrt(mean_squared_error(y_test, y_pred))
print ('RMSE (Root Mean Squared Error) = ', rmse)

r2 = r2_score(y_test, y_pred)
print ('R2 = ', r2)

RMSE (Root Mean Squared Error) =  5.201541726768596
R2 =  0.7278215298866197
